spring.datasource.url=jdbc:postgresql://db:5432/fluir
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}